export {
  UltimateBackdrop,
  UltimateCtaPanel,
  UltimateFeatureCardRail,
  UltimateFocusDiagram,
  UltimateHeroPanel,
  UltimateMetricBars,
  UltimateNumberStrip,
  UltimatePlatformOverlay,
  UltimateStage,
  UltimateStepFlow,
  UltimateSubtitleBar,
  UltimateTagMatrix,
  UltimateTerminalPanel,
  UltimateCodePanel,
} from './UltimateElements';
export {UltimateSceneTransition} from './UltimateSceneTransition';
export type {
  UltimateCodeLine,
  UltimateCodePanelProps,
  UltimateCtaPanelProps,
  UltimateFeatureCardItem,
  UltimateFeatureCardRailProps,
  UltimateFocusDiagramProps,
  UltimateHeroPanelProps,
  UltimateMetricBarsProps,
  UltimateMetricItem,
  UltimateNumberStripProps,
  UltimatePlatformOverlayProps,
  UltimateStepFlowProps,
  UltimateStepItem,
  UltimateStripItem,
  UltimateSubtitleBarProps,
  UltimateTagChip,
  UltimateTagMatrixProps,
  UltimateTerminalPanelProps,
} from './types';
export type {
  UltimateCodeScene,
  UltimateCtaScene,
  UltimateFeatureRailScene,
  UltimateFocusScene,
  UltimateHeroScene,
  UltimateMetricsScene,
  UltimateNumberStripScene,
  UltimateProjectConfig,
  UltimateTransitionConfig,
  UltimateTransitionPreset,
  UltimateSceneConfig,
  UltimateSceneFamily,
  UltimateSceneTemplateProps,
  UltimateStepFlowScene,
  UltimateTagMatrixScene,
  UltimateTerminalScene,
  ResolvedUltimateProjectConfig,
  ResolvedUltimateSceneConfig,
  ResolvedUltimateHeroScene,
  ResolvedUltimateFeatureRailScene,
  ResolvedUltimateFocusScene,
  ResolvedUltimateNumberStripScene,
  ResolvedUltimateStepFlowScene,
  ResolvedUltimateTerminalScene,
  ResolvedUltimateTagMatrixScene,
  ResolvedUltimateCodeScene,
  ResolvedUltimateMetricsScene,
  ResolvedUltimateCtaScene,
  ResolvedUltimateTransitionConfig,
} from './project';
export {
  estimateUltimateSceneDuration,
  getUltimateProjectDuration,
  normalizeUltimateProjectConfig,
} from './project';
export {ultimateAccents, ultimateKitTokens, ultimateKitVideo, resolveUltimateAccent, ultimateGlow} from './tokens';
