export const SKILL_ICON_KEYS = [
  'code',
  'terminal',
  'bug',
  'test-tube',
  'file-code-2',
  'git-compare-arrows',
  'circle-check-big',
  'shield-check',
  'film',
  'braces',
  'play',
  'panels-top-left',
  'camera',
  'captions',
  'audio-waveform',
  'timer',
  'presentation',
  'chart-no-axes-column-increasing',
  'chart-pie',
  'shapes',
  'mouse-pointer-2',
  'table-2',
  'image',
  'route',
  'pen-tool',
  'file-text',
  'link-2',
  'unlink-2',
  'workflow',
  'lightbulb',
  'quote',
  'book-open',
  'image-plus',
  'clapperboard',
  'code-xml',
  'blocks',
  'zap',
  'bot',
  'brain-circuit',
  'plug-zap',
  'wand-sparkles',
  'layout-template',
  'type',
  'palette',
  'grid-3x3',
  'ruler',
  'swatch-book',
  'panel-top',
  'component',
  'database',
  'chart-line',
  'gauge',
  'sigma',
  'binary',
  'search',
  'file-search',
  'bookmark',
  'external-link',
  'mic-vocal',
  'audio-lines',
  'volume-2',
  'speech',
  'badge-check',
  'shield-alert',
  'list-checks',
  'scan-search',
  'circle-help',
  'scan-line',
  'move-right',
  'focus',
  'maximize-2',
  'send',
  'share-2',
  'download',
  'message-circle',
  'rocket',
] as const;

export type SkillIconKey = (typeof SKILL_ICON_KEYS)[number];

export const ICON_PACKS = {
  coding: ['code', 'terminal', 'bug', 'test-tube', 'file-code-2', 'git-compare-arrows', 'circle-check-big', 'shield-check'],
  video: ['film', 'braces', 'play', 'panels-top-left', 'camera', 'captions', 'audio-waveform', 'timer'],
  slides: ['presentation', 'chart-no-axes-column-increasing', 'chart-pie', 'shapes', 'mouse-pointer-2', 'table-2', 'image', 'route'],
  content: ['pen-tool', 'file-text', 'link-2', 'unlink-2', 'workflow', 'lightbulb', 'quote', 'book-open', 'image-plus'],
  agent: ['clapperboard', 'code-xml', 'blocks', 'zap', 'bot', 'brain-circuit', 'plug-zap', 'wand-sparkles'],
  ui: ['layout-template', 'type', 'palette', 'grid-3x3', 'ruler', 'swatch-book', 'panel-top', 'component'],
  data: ['database', 'chart-line', 'gauge', 'sigma', 'binary'],
  research: ['search', 'file-search', 'bookmark', 'external-link'],
  narration: ['mic-vocal', 'audio-lines', 'volume-2', 'speech'],
  qa: ['badge-check', 'shield-alert', 'list-checks', 'scan-search', 'circle-help'],
  motion: ['scan-line', 'move-right', 'focus', 'maximize-2'],
  publish: ['send', 'share-2', 'download', 'message-circle', 'rocket'],
} as const satisfies Record<string, readonly SkillIconKey[]>;

export type SkillIconPack = keyof typeof ICON_PACKS;
