import type { FxPresetId, ParticleLevel, ShotDirector, ShotTheme } from './types';

const FX_PRESETS: Record<FxPresetId, ShotTheme> = {
  'proof-grid': {
    fxPreset: 'proof-grid',
    accentColor: '#69f0ae',
    secondaryColor: '#00d4ff',
    tertiaryColor: '#ffd166',
    dangerColor: '#ff6b6b',
    bgColor: '#07121f',
    bgGradient: 'radial-gradient(circle at 20% 20%, rgba(105,240,174,0.18), transparent 40%), radial-gradient(circle at 80% 18%, rgba(0,212,255,0.18), transparent 38%), linear-gradient(160deg, #07121f 0%, #0b1930 55%, #050b15 100%)',
    particleCount: 52,
    particleColors: ['#69f0ae', '#00d4ff', '#ffffff'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.12,
    overlayMode: 'hybrid',
    showProgress: false,
    badgeVariant: 'top',
    captionFontSize: 28,
  },
  'warning-pulse': {
    fxPreset: 'warning-pulse',
    accentColor: '#ff8a4c',
    secondaryColor: '#ff4d6d',
    tertiaryColor: '#ffd166',
    dangerColor: '#ff3b30',
    bgColor: '#1a0b12',
    bgGradient: 'radial-gradient(circle at 18% 24%, rgba(255,77,109,0.18), transparent 36%), radial-gradient(circle at 80% 72%, rgba(255,138,76,0.16), transparent 36%), linear-gradient(170deg, #16070d 0%, #220c14 50%, #09040a 100%)',
    particleCount: 34,
    particleColors: ['#ff8a4c', '#ff4d6d', '#ffd166'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.08,
    overlayMode: 'slide',
    showProgress: false,
    badgeVariant: 'hot',
    captionFontSize: 30,
  },
  'signal-flow': {
    fxPreset: 'signal-flow',
    accentColor: '#00d4ff',
    secondaryColor: '#7cf29c',
    tertiaryColor: '#8f7cff',
    dangerColor: '#ff6b6b',
    bgColor: '#07111c',
    bgGradient: 'radial-gradient(circle at 50% 20%, rgba(0,212,255,0.14), transparent 35%), radial-gradient(circle at 18% 80%, rgba(124,242,156,0.14), transparent 32%), linear-gradient(180deg, #06111a 0%, #091623 52%, #04090f 100%)',
    particleCount: 48,
    particleColors: ['#00d4ff', '#7cf29c', '#8f7cff', '#ffffff'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.1,
    overlayMode: 'hybrid',
    showProgress: true,
    badgeVariant: 'new',
    captionFontSize: 28,
  },
  'heat-map': {
    fxPreset: 'heat-map',
    accentColor: '#00ff88',
    secondaryColor: '#00d4ff',
    tertiaryColor: '#ffe066',
    dangerColor: '#ff5a5f',
    bgColor: '#061017',
    bgGradient: 'radial-gradient(circle at 75% 20%, rgba(0,255,136,0.16), transparent 36%), radial-gradient(circle at 28% 76%, rgba(255,90,95,0.12), transparent 30%), linear-gradient(180deg, #061017 0%, #0c1c2a 52%, #060b10 100%)',
    particleCount: 44,
    particleColors: ['#00ff88', '#00d4ff', '#ffe066'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.1,
    overlayMode: 'tags',
    showProgress: true,
    badgeVariant: 'new',
    captionFontSize: 28,
  },
  'social-proof': {
    fxPreset: 'social-proof',
    accentColor: '#ffd166',
    secondaryColor: '#00d4ff',
    tertiaryColor: '#7cf29c',
    dangerColor: '#ff6b6b',
    bgColor: '#121018',
    bgGradient: 'radial-gradient(circle at 22% 18%, rgba(255,209,102,0.14), transparent 35%), radial-gradient(circle at 74% 70%, rgba(0,212,255,0.12), transparent 32%), linear-gradient(165deg, #120f18 0%, #171325 55%, #0b0911 100%)',
    particleCount: 28,
    particleColors: ['#ffd166', '#00d4ff', '#ffffff'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.05,
    overlayMode: 'hybrid',
    showProgress: false,
    badgeVariant: 'live',
    captionFontSize: 29,
  },
  'cta-burst': {
    fxPreset: 'cta-burst',
    accentColor: '#00d4ff',
    secondaryColor: '#ffd166',
    tertiaryColor: '#ff77e9',
    dangerColor: '#ff5a5f',
    bgColor: '#0a0a1a',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(0,212,255,0.22), transparent 36%), radial-gradient(circle at 30% 75%, rgba(255,209,102,0.16), transparent 30%), linear-gradient(180deg, #090913 0%, #121220 45%, #04040a 100%)',
    particleCount: 64,
    particleColors: ['#00d4ff', '#ffd166', '#ff77e9', '#ffffff'],
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
    gridOpacity: 0.12,
    overlayMode: 'hybrid',
    showProgress: true,
    badgeVariant: 'hot',
    captionFontSize: 30,
  },
};

const PARTICLE_LEVEL_MAP: Record<ParticleLevel, Pick<ShotTheme, 'particleDensityMultiplier' | 'particleOpacityScale' | 'particleSpeedMultiplier'>> = {
  none: {
    particleDensityMultiplier: 0,
    particleOpacityScale: 0,
    particleSpeedMultiplier: 0,
  },
  low: {
    particleDensityMultiplier: 0.7,
    particleOpacityScale: 0.72,
    particleSpeedMultiplier: 0.86,
  },
  medium: {
    particleDensityMultiplier: 1,
    particleOpacityScale: 1,
    particleSpeedMultiplier: 1,
  },
  high: {
    particleDensityMultiplier: 1.28,
    particleOpacityScale: 1.18,
    particleSpeedMultiplier: 1.12,
  },
};

export const resolveShotTheme = (director: ShotDirector): ShotTheme => {
  const preset = FX_PRESETS[director.fxPreset];
  const particleProfile = PARTICLE_LEVEL_MAP[director.particleLevel || 'medium'];
  return {
    ...preset,
    accentColor: director.accentColor || preset.accentColor,
    secondaryColor: director.secondaryColor || preset.secondaryColor,
    tertiaryColor: director.tertiaryColor || preset.tertiaryColor,
    dangerColor: director.dangerColor || preset.dangerColor,
    bgColor: director.bgColor || preset.bgColor,
    particleDensityMultiplier: particleProfile.particleDensityMultiplier,
    particleOpacityScale: particleProfile.particleOpacityScale,
    particleSpeedMultiplier: particleProfile.particleSpeedMultiplier,
    overlayMode: director.overlayMode || preset.overlayMode,
    badgeVariant: director.badge?.variant || preset.badgeVariant,
  };
};
