import type { ShotDirector } from './types';

export const SHOT_DIRECTIONS_V4H: ShotDirector[] = [
  {
    id: 'shot-01',
    title: 'GitHub 4.7万星',
    kicker: '全球热榜第一的证据镜头',
    family: 'proof',
    fxPreset: 'proof-grid',
    particleLevel: 'low',
    iconIds: ['github', 'graph', 'spark'],
    highlightWords: ['4.7万星', '热榜第一', 'OpenClaw'],
    tags: [{ label: 'GitHub Heat' }, { label: 'Proof First' }, { label: 'Signal' }],
    badge: { label: 'TOP 1', variant: 'top' },
  },
  {
    id: 'shot-02',
    title: '记忆断裂',
    kicker: '重启即失忆的产品痛点',
    family: 'product',
    fxPreset: 'warning-pulse',
    particleLevel: 'low',
    iconIds: ['memory', 'automation'],
    highlightWords: ['重启', '全没了', 'Hermes'],
    tags: [{ label: 'State Reset' }, { label: 'Memory Gap' }],
    badge: { label: 'Pain Point', variant: 'hot' },
  },
  {
    id: 'shot-03',
    title: 'OpenClaw 起势',
    kicker: '平台接入 + 插件生态',
    family: 'comparison',
    fxPreset: 'signal-flow',
    particleLevel: 'medium',
    iconIds: ['telegram', 'discord', 'slack', 'plugin'],
    highlightWords: ['OpenClaw', '消息平台', '插件生态'],
    tags: [{ label: 'Channels' }, { label: 'ClawHub' }, { label: 'Breadth' }],
  },
  {
    id: 'shot-04',
    title: '多平台接入',
    kicker: '即时接入能力',
    family: 'product',
    fxPreset: 'proof-grid',
    particleLevel: 'low',
    iconIds: ['telegram', 'discord', 'slack', 'whatsapp'],
    highlightWords: ['Telegram', 'Discord', 'Slack', 'WhatsApp'],
    tags: [{ label: 'Message Ops' }, { label: 'Ready-to-use' }],
  },
  {
    id: 'shot-05',
    title: '插件生态',
    kicker: '工具连接器的广度',
    family: 'product',
    fxPreset: 'signal-flow',
    particleLevel: 'medium',
    iconIds: ['plugin', 'automation', 'skills'],
    highlightWords: ['插件生态', '文件读写', 'Shell操作'],
    tags: [{ label: 'Plugin Mesh' }, { label: 'Tool Surface' }],
  },
  {
    id: 'shot-06',
    title: '连接一切',
    kicker: '工具被接进 AI 工作流',
    family: 'system',
    fxPreset: 'signal-flow',
    particleLevel: 'medium',
    iconIds: ['plugin', 'timeline', 'speed'],
    highlightWords: ['连接器', '工具', '稳'],
    tags: [{ label: 'Workflow Link' }, { label: 'Stable' }],
  },
  {
    id: 'shot-07',
    title: '问题一：上下文膨胀',
    kicker: '成本与延迟同步走高',
    family: 'data',
    fxPreset: 'warning-pulse',
    particleLevel: 'low',
    iconIds: ['cost', 'timeline', 'graph'],
    highlightWords: ['上下文膨胀', 'token', '成本'],
    tags: [{ label: 'Token Tax' }, { label: 'Latency' }, { label: 'Cost Curve' }],
    badge: { label: 'Warning', variant: 'hot' },
  },
  {
    id: 'shot-08',
    title: '问题二：无状态',
    kicker: '经验无法累积',
    family: 'comparison',
    fxPreset: 'warning-pulse',
    particleLevel: 'low',
    iconIds: ['memory', 'timeline'],
    highlightWords: ['无状态', '不记得', '三个月'],
    tags: [{ label: 'No Memory' }, { label: 'Reset Each Time' }],
  },
  {
    id: 'shot-09',
    title: '问题三：半自动',
    kicker: '没有自主规划',
    family: 'comparison',
    fxPreset: 'warning-pulse',
    particleLevel: 'low',
    iconIds: ['automation', 'loop'],
    highlightWords: ['半自动', '一步一步', '停在那'],
    tags: [{ label: 'Manual Steering' }, { label: 'No Autonomy' }],
  },
  {
    id: 'shot-10',
    title: '技术根因',
    kicker: 'O(n²) 注意力成本曲线',
    family: 'data',
    fxPreset: 'heat-map',
    particleLevel: 'medium',
    iconIds: ['graph', 'cost', 'speed'],
    highlightWords: ['O(n²)', '平方增长', '推理成本'],
    tags: [{ label: 'Transformer Cost' }, { label: 'Scaling Law' }, { label: 'Root Cause' }],
    badge: { label: 'Deep Dive', variant: 'new' },
  },
  {
    id: 'shot-11',
    title: 'Hermes 破局',
    kicker: '提取替代堆积',
    family: 'system',
    fxPreset: 'signal-flow',
    particleLevel: 'high',
    iconIds: ['skills', 'memory', 'automation'],
    highlightWords: ['技能系统', '提取', '不堆'],
    tags: [{ label: 'Extract' }, { label: 'Reuse' }, { label: 'Skill Loop' }],
  },
  {
    id: 'shot-12',
    title: 'Hermes 热度',
    kicker: '开源后两个月的外部信号',
    family: 'proof',
    fxPreset: 'proof-grid',
    particleLevel: 'low',
    iconIds: ['github', 'graph', 'spark'],
    highlightWords: ['2月25日', '4.7万星', '3536次提交'],
    tags: [{ label: 'Open Source' }, { label: 'v0.8.0' }, { label: 'Momentum' }],
    badge: { label: 'Momentum', variant: 'top' },
  },
  {
    id: 'shot-13',
    title: '自我进化',
    kicker: '每次成功都沉淀',
    family: 'system',
    fxPreset: 'signal-flow',
    particleLevel: 'high',
    iconIds: ['loop', 'skills', 'automation'],
    highlightWords: ['自我进化', '复用', '技能'],
    tags: [{ label: 'Learning Loop' }, { label: 'Self Evolution' }],
  },
  {
    id: 'shot-14',
    title: '技能系统',
    kicker: '执行成功后自动提取',
    family: 'system',
    fxPreset: 'signal-flow',
    particleLevel: 'high',
    iconIds: ['skills', 'automation', 'memory'],
    highlightWords: ['执行成功', '自动提取', '技能库'],
    tags: [{ label: 'Capture' }, { label: 'Store' }, { label: 'Recall' }],
  },
  {
    id: 'shot-15',
    title: '闭环学习架构',
    kicker: '执行、分析、提取、存储',
    family: 'system',
    fxPreset: 'signal-flow',
    particleLevel: 'high',
    iconIds: ['loop', 'automation', 'timeline'],
    highlightWords: ['闭环学习', '执行', '存储'],
    tags: [{ label: 'Closed Loop' }, { label: 'System Design' }],
  },
  {
    id: 'shot-16',
    title: '开环 vs 闭环',
    kicker: '增长方向完全相反',
    family: 'comparison',
    fxPreset: 'heat-map',
    particleLevel: 'medium',
    iconIds: ['loop', 'graph', 'skills'],
    highlightWords: ['开环系统', '闭环系统', '递减'],
    tags: [{ label: 'Open Loop' }, { label: 'Closed Loop' }, { label: 'Compounding' }],
  },
  {
    id: 'shot-17',
    title: 'Reddit 用户案例',
    kicker: '来自真实迁移反馈',
    family: 'quote',
    fxPreset: 'social-proof',
    particleLevel: 'low',
    iconIds: ['reddit', 'spark', 'skills'],
    highlightWords: ['Reddit', '丝滑换壳', '5美元'],
    tags: [{ label: 'Social Proof' }, { label: '$5 / month' }, { label: 'No Crash' }],
    badge: { label: 'User Voice', variant: 'live' },
  },
  {
    id: 'shot-18',
    title: '本地部署',
    kicker: '数据不离开自己的机器',
    family: 'proof',
    fxPreset: 'proof-grid',
    particleLevel: 'low',
    iconIds: ['ollama', 'shield', 'memory'],
    highlightWords: ['本地部署', 'Ollama', '数据不离'],
    tags: [{ label: 'Local-first' }, { label: 'Privacy' }, { label: 'Control' }],
  },
  {
    id: 'shot-19',
    title: '设计哲学',
    kicker: '你教它，还是它自己学会',
    family: 'comparison',
    fxPreset: 'heat-map',
    particleLevel: 'medium',
    iconIds: ['memory', 'skills', 'loop'],
    highlightWords: ['设计哲学', '你来教它', '它自己学会'],
    tags: [{ label: 'OpenClaw' }, { label: 'Hermes' }, { label: 'Philosophy' }],
    badge: { label: 'Core Thesis', variant: 'new' },
  },
  {
    id: 'shot-20',
    title: '你的选择是？',
    kicker: '收束观点并引导互动',
    family: 'cta',
    fxPreset: 'cta-burst',
    particleLevel: 'medium',
    iconIds: ['spark', 'loop', 'github'],
    highlightWords: ['OpenClaw', 'Hermes', '关注我'],
    tags: [{ label: 'Comment' }, { label: 'Share' }, { label: 'Follow' }],
    badge: { label: 'CTA', variant: 'hot' },
  },
];

const SHOT_DIRECTION_MAP = Object.fromEntries(
  SHOT_DIRECTIONS_V4H.map((shot) => [shot.id, shot])
) as Record<string, ShotDirector>;

export const getShotDirector = (id: string, index: number): ShotDirector => {
  return SHOT_DIRECTION_MAP[id] || {
    id,
    title: `Shot ${index + 1}`,
    family: 'product',
    fxPreset: 'signal-flow',
    iconIds: ['spark'],
  };
};
